export enum NotificationType {
  // Système
  SYSTEM = 'SYSTEM',
  
  // Posts
  POST_CREATED = 'POST_CREATED',
  POST_LIKED = 'POST_LIKED',
  POST_COMMENTED = 'POST_COMMENTED',
  
  // Stories
  STORY_CREATED = 'STORY_CREATED',
  STORY_VIEWED = 'STORY_VIEWED',
  
  // Places
  PLACE_CREATED = 'PLACE_CREATED',
  PLACE_LIKED = 'PLACE_LIKED',
  PLACE_COMMENTED = 'PLACE_COMMENTED',
  
  // Follow
  FOLLOW_REQUEST = 'FOLLOW_REQUEST',
  FOLLOW_ACCEPTED = 'FOLLOW_ACCEPTED',
  FOLLOW_REJECTED = 'FOLLOW_REJECTED',
  
  // Activités
  ACTIVITY_CREATED = 'ACTIVITY_CREATED',
  ACTIVITY_UPDATED = 'ACTIVITY_UPDATED',
  ACTIVITY_DELETED = 'ACTIVITY_DELETED',
  ACTIVITY_VOTE = 'ACTIVITY_VOTE',
  
  // Projets
  PROJECT_INVITATION = 'PROJECT_INVITATION',
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  PROJECT_JOINED = 'PROJECT_JOINED',
  PROJECT_LEFT = 'PROJECT_LEFT',
  
  // Commentaires
  COMMENT = 'COMMENT',
  COMMENT_ADDED = 'COMMENT_ADDED',
  COMMENT_LIKED = 'COMMENT_LIKED',
  COMMENT_REPLIED = 'COMMENT_REPLIED',
  
  // Votes
  VOTE = 'VOTE',
  VOTE_ADDED = 'VOTE_ADDED',
  VOTE_UPDATED = 'VOTE_UPDATED',
  VOTE_REMOVED = 'VOTE_REMOVED',
  VOTE_DELETED = 'VOTE_DELETED',
  
  // Hébergement
  ACCOMMODATION_SELECTED = 'ACCOMMODATION_SELECTED',
  ACCOMMODATION_UNSELECTED = 'ACCOMMODATION_UNSELECTED',
  ACCOMMODATION_CREATED = 'ACCOMMODATION_CREATED',
  ACCOMMODATION_VOTE = 'ACCOMMODATION_VOTE',
  ACCOMMODATION_VOTE_DELETED = 'ACCOMMODATION_VOTE_DELETED',
  
  // Transport
  TRANSPORT_SELECTED = 'TRANSPORT_SELECTED',
  TRANSPORT_UNSELECTED = 'TRANSPORT_UNSELECTED',
  
  // Dates
  DATE_SELECTED = 'DATE_SELECTED',
  DATE_UNSELECTED = 'DATE_UNSELECTED',
  DATE_VOTE = 'DATE_VOTE',
  
  // Destinations
  DESTINATION_SELECTED = 'DESTINATION_SELECTED',
  DESTINATION_UNSELECTED = 'DESTINATION_UNSELECTED',
  DESTINATION_VOTE = 'DESTINATION_VOTE',
  
  // Planning
  PLANNING_ACTIVITY_ADDED = 'PLANNING_ACTIVITY_ADDED',
  PLANNING_ACTIVITY_UPDATED = 'PLANNING_ACTIVITY_UPDATED',
  PLANNING_ACTIVITY_REMOVED = 'PLANNING_ACTIVITY_REMOVED',
} 