export enum NotificationType {
  // ... existing code ...
  PLANNING_CREATED = 'PLANNING_CREATED',
  PLANNING_ACTIVITY_ADDED = 'PLANNING_ACTIVITY_ADDED',
  PLANNING_ACTIVITY_UPDATED = 'PLANNING_ACTIVITY_UPDATED',
  PLANNING_ACTIVITY_REMOVED = 'PLANNING_ACTIVITY_REMOVED',
  // ... existing code ...
} 